import { StyleSheet } from 'react-native';
import { colors } from './colors';

export const detailBadgeStyles = StyleSheet.create({
  badge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
  },
  text: { fontSize: 12, fontWeight: '500' as const },
});

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.bg },
  scrollContent: { padding: 16, paddingBottom: 32 },
  centered: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  error: { color: colors.red, marginBottom: 16, fontSize: 14, textAlign: 'center' },
  errorActions: { flexDirection: 'row', gap: 12, alignItems: 'center' },
  retryButton: { paddingHorizontal: 20, paddingVertical: 12, backgroundColor: colors.indigo600, borderRadius: 8 },
  retryButtonText: { color: colors.white, fontWeight: '600', fontSize: 16 },
  backBtn: { paddingHorizontal: 20, paddingVertical: 12, backgroundColor: colors.slate200, borderRadius: 8 },
  backBtnText: { color: colors.slate800, fontWeight: '600' },
  backLink: { marginBottom: 24 },
  backLinkText: { fontSize: 14, fontWeight: '500', color: colors.slate600 },
  card: {
    backgroundColor: colors.white,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.slate200,
    overflow: 'hidden',
    marginBottom: 24,
  },
  cardHeader: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
    padding: 20,
    paddingBottom: 0,
  },
  title: { fontSize: 22, fontWeight: '600', color: colors.slate900, flex: 1 },
  metaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 24,
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 16,
  },
  metaItem: {},
  metaLabel: { fontSize: 12, fontWeight: '500', color: colors.slate500, marginBottom: 2 },
  metaValue: { fontSize: 14, color: colors.slate700 },
  cardBody: { padding: 20, paddingTop: 0 },
  body: { fontSize: 16, color: colors.slate700, lineHeight: 24 },
  actions: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginBottom: 24 },
  btnPrimary: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: colors.indigo600,
    borderRadius: 8,
  },
  btnPrimaryText: { color: colors.white, fontWeight: '600', fontSize: 14 },
  btnAmber: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: colors.amber,
    borderRadius: 8,
  },
  btnAmberText: { color: colors.white, fontWeight: '600', fontSize: 14 },
  btnGreen: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: colors.emerald,
    borderRadius: 8,
  },
  btnGreenText: { color: colors.white, fontWeight: '600', fontSize: 14 },
  auditSection: {
    backgroundColor: colors.white,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.slate200,
    padding: 20,
  },
  auditTitle: { fontSize: 18, fontWeight: '600', color: colors.slate900, marginBottom: 12 },
  auditEmpty: { paddingVertical: 32, alignItems: 'center' },
  auditRow: { marginBottom: 16 },
  auditRowTop: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center' },
  auditAction: { fontWeight: '600', color: colors.slate700, fontSize: 14 },
  auditMuted: { fontSize: 14, color: colors.slate400 },
  auditArrow: { fontSize: 14, color: colors.slate300 },
  auditTo: { fontSize: 14, color: colors.slate600, fontWeight: '500' },
  auditMeta: { fontSize: 12, color: colors.slate500, marginTop: 4 },
  muted: { fontSize: 13, color: colors.slate500 },
});
