import { StyleSheet } from 'react-native';
import { colors } from './colors';

export const badgeStyles = StyleSheet.create({
  badge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
    alignSelf: 'flex-start',
  },
  text: { fontSize: 12, fontWeight: '500' as const },
});

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.bg },
  pageHeader: {
    paddingHorizontal: 16,
    paddingTop: 24,
    paddingBottom: 8,
  },
  title: { fontSize: 24, fontWeight: '600', color: colors.slate900 },
  count: { fontSize: 14, color: colors.slate500, marginTop: 4 },
  filters: {
    flexDirection: 'column',
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginBottom: 8,
    gap: 12,
  },
  filterBlock: {
    width: '100%',
  },
  filterLabel: {
    fontSize: 12,
    fontWeight: '500',
    color: colors.slate500,
    marginBottom: 6,
  },
  statusPills: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  pill: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.slate200,
  },
  pillSelected: { borderColor: colors.indigo500, backgroundColor: colors.indigo50 },
  pillText: { fontSize: 14, color: colors.slate600 },
  pillTextSelected: { fontSize: 14, fontWeight: '600', color: colors.indigo600 },
  sectorButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.slate200,
    backgroundColor: colors.white,
    minWidth: 140,
  },
  sectorButtonText: { fontSize: 14, color: colors.slate700 },
  sectorChevron: { fontSize: 10, color: colors.slate500 },
  dropdown: {
    marginTop: 4,
    backgroundColor: colors.white,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.slate200,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
    maxHeight: 220,
  },
  dropdownScroll: {
    maxHeight: 216,
  },
  dropdownOption: {
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.slate100,
  },
  dropdownOptionLast: {
    borderBottomWidth: 0,
  },
  dropdownOptionSelected: {
    backgroundColor: colors.indigo50,
  },
  dropdownOptionText: { fontSize: 14, color: colors.slate800 },
  dropdownOptionTextSelected: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.indigo600,
  },
  offlineRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 8,
    gap: 8,
  },
  offlineLabel: { fontSize: 14, color: colors.slate600 },
  offlineBanner: { backgroundColor: colors.amberBg, padding: 10, paddingHorizontal: 16 },
  offlineText: { fontSize: 13, color: colors.amberText, fontWeight: '500' },
  centered: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  muted: { color: colors.slate500, fontSize: 14 },
  mutedSmall: { color: colors.slate400, fontSize: 13, marginTop: 4 },
  error: { color: colors.red, fontSize: 14, marginBottom: 16, textAlign: 'center' },
  retryButton: {
    backgroundColor: colors.indigo600,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
  },
  retryButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: '600',
  },
  listContent: { padding: 16, paddingTop: 8, paddingBottom: 24 },
  card: {
    backgroundColor: colors.white,
    padding: 16,
    marginBottom: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.slate200,
  },
  cardTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  cardTitle: { fontSize: 18, fontWeight: '600', color: colors.slate900, flex: 1 },
  cardMeta: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 12 },
  cardSector: { fontSize: 14, fontWeight: '500', color: colors.slate600 },
  cardDot: { fontSize: 14, color: colors.slate400 },
  cardDate: { fontSize: 12, color: colors.slate400 },
  cardBody: { fontSize: 14, color: colors.slate600, marginTop: 12, lineHeight: 20 },
});
